<template>
  <footer class="footer">
      <div class="container">
        <p class="text-muted">
          <a href="http://traversymedia.com/">Copy Right @ Traversy Media</a>
        </p>
      </div>
    </footer>
</template>
<script>
export default {
  name: 'footerTemplate'
}
</script>
<style>
  .footer {
    position: absolute;
    bottom: 0;
    width: 100%;
    height: 60px;
    background-color: #f5f5f5;
}
</style>